/*
 * AM243 Devices Info
 *
 * Copyright (C) 2020 Texas Instruments Incorporated - https://www.ti.com/
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <tisci.h>
#include <socinfo.h>

struct ti_sci_devices_info am243x_devices_info[] = {
	{0, "TISCI_DEV_ADC0"},
	{1, "TISCI_DEV_CMP_EVENT_INTROUTER0"},
	{2, "TISCI_DEV_DBGSUSPENDROUTER0"},
	{3, "TISCI_DEV_MAIN_GPIOMUX_INTROUTER0"},
	{5, "TISCI_DEV_MCU_MCU_GPIOMUX_INTROUTER0"},
	{6, "TISCI_DEV_TIMESYNC_EVENT_INTROUTER0"},
	{7, "TISCI_DEV_MCU_M4FSS0"},
	{8, "TISCI_DEV_MCU_M4FSS0_CBASS_0"},
	{9, "TISCI_DEV_MCU_M4FSS0_CORE0"},
	{13, "TISCI_DEV_CPSW0"},
	{14, "TISCI_DEV_CPT2_AGGR0"},
	{15, "TISCI_DEV_STM0"},
	{16, "TISCI_DEV_DCC0"},
	{17, "TISCI_DEV_DCC1"},
	{18, "TISCI_DEV_DCC2"},
	{19, "TISCI_DEV_DCC3"},
	{20, "TISCI_DEV_DCC4"},
	{21, "TISCI_DEV_DCC5"},
	{22, "TISCI_DEV_DMSC0"},
	{23, "TISCI_DEV_MCU_DCC0"},
	{24, "TISCI_DEV_DEBUGSS_WRAP0"},
	{25, "TISCI_DEV_DMASS0"},
	{26, "TISCI_DEV_DMASS0_BCDMA_0"},
	{27, "TISCI_DEV_DMASS0_CBASS_0"},
	{28, "TISCI_DEV_DMASS0_INTAGGR_0"},
	{29, "TISCI_DEV_DMASS0_IPCSS_0"},
	{30, "TISCI_DEV_DMASS0_PKTDMA_0"},
	{33, "TISCI_DEV_DMASS0_RINGACC_0"},
	{35, "TISCI_DEV_MCU_TIMER0"},
	{36, "TISCI_DEV_TIMER0"},
	{37, "TISCI_DEV_TIMER1"},
	{38, "TISCI_DEV_TIMER2"},
	{39, "TISCI_DEV_TIMER3"},
	{40, "TISCI_DEV_TIMER4"},
	{41, "TISCI_DEV_TIMER5"},
	{42, "TISCI_DEV_TIMER6"},
	{43, "TISCI_DEV_TIMER7"},
	{44, "TISCI_DEV_TIMER8"},
	{45, "TISCI_DEV_TIMER9"},
	{46, "TISCI_DEV_TIMER10"},
	{47, "TISCI_DEV_TIMER11"},
	{48, "TISCI_DEV_MCU_TIMER1"},
	{49, "TISCI_DEV_MCU_TIMER2"},
	{50, "TISCI_DEV_MCU_TIMER3"},
	{51, "TISCI_DEV_ECAP0"},
	{52, "TISCI_DEV_ECAP1"},
	{53, "TISCI_DEV_ECAP2"},
	{54, "TISCI_DEV_ELM0"},
	{55, "TISCI_DEV_EMIF_DATA_0_VD"},
	{57, "TISCI_DEV_MMCSD0"},
	{58, "TISCI_DEV_MMCSD1"},
	{59, "TISCI_DEV_EQEP0"},
	{60, "TISCI_DEV_EQEP1"},
	{61, "TISCI_DEV_GTC0"},
	{62, "TISCI_DEV_EQEP2"},
	{63, "TISCI_DEV_ESM0"},
	{64, "TISCI_DEV_MCU_ESM0"},
	{65, "TISCI_DEV_FSIRX0"},
	{66, "TISCI_DEV_FSIRX1"},
	{67, "TISCI_DEV_FSIRX2"},
	{68, "TISCI_DEV_FSIRX3"},
	{69, "TISCI_DEV_FSIRX4"},
	{70, "TISCI_DEV_FSIRX5"},
	{71, "TISCI_DEV_FSITX0"},
	{72, "TISCI_DEV_FSITX1"},
	{73, "TISCI_DEV_FSS0"},
	{74, "TISCI_DEV_FSS0_FSAS_0"},
	{75, "TISCI_DEV_FSS0_OSPI_0"},
	{76, "TISCI_DEV_GICSS0"},
	{77, "TISCI_DEV_GPIO0"},
	{78, "TISCI_DEV_GPIO1"},
	{79, "TISCI_DEV_MCU_GPIO0"},
	{80, "TISCI_DEV_GPMC0"},
	{81, "TISCI_DEV_PRU_ICSSG0"},
	{82, "TISCI_DEV_PRU_ICSSG1"},
	{83, "TISCI_DEV_LED0"},
	{84, "TISCI_DEV_CPTS0"},
	{85, "TISCI_DEV_DDPA0"},
	{86, "TISCI_DEV_EPWM0"},
	{87, "TISCI_DEV_EPWM1"},
	{88, "TISCI_DEV_EPWM2"},
	{89, "TISCI_DEV_EPWM3"},
	{90, "TISCI_DEV_EPWM4"},
	{91, "TISCI_DEV_EPWM5"},
	{92, "TISCI_DEV_EPWM6"},
	{93, "TISCI_DEV_EPWM7"},
	{94, "TISCI_DEV_EPWM8"},
	{95, "TISCI_DEV_VTM0"},
	{96, "TISCI_DEV_MAILBOX0"},
	{97, "TISCI_DEV_MAIN2MCU_VD"},
	{98, "TISCI_DEV_MCAN0"},
	{99, "TISCI_DEV_MCAN1"},
	{100, "TISCI_DEV_MCU_MCRC64_0"},
	{101, "TISCI_DEV_MCU2MAIN_VD"},
	{102, "TISCI_DEV_I2C0"},
	{103, "TISCI_DEV_I2C1"},
	{104, "TISCI_DEV_I2C2"},
	{105, "TISCI_DEV_I2C3"},
	{106, "TISCI_DEV_MCU_I2C0"},
	{107, "TISCI_DEV_MCU_I2C1"},
	{114, "TISCI_DEV_PCIE0"},
	{119, "TISCI_DEV_R5FSS0"},
	{120, "TISCI_DEV_R5FSS1"},
	{121, "TISCI_DEV_R5FSS0_CORE0"},
	{122, "TISCI_DEV_R5FSS0_CORE1"},
	{123, "TISCI_DEV_R5FSS1_CORE0"},
	{124, "TISCI_DEV_R5FSS1_CORE1"},
	{125, "TISCI_DEV_RTI0"},
	{126, "TISCI_DEV_RTI1"},
	{127, "TISCI_DEV_RTI8"},
	{128, "TISCI_DEV_RTI9"},
	{130, "TISCI_DEV_RTI10"},
	{131, "TISCI_DEV_RTI11"},
	{132, "TISCI_DEV_MCU_RTI0"},
	{133, "TISCI_DEV_SA2_UL0"},
	{134, "TISCI_DEV_COMPUTE_CLUSTER0"},
	{138, "TISCI_DEV_DDR16SS0"},
	{139, "TISCI_DEV_PSC0"},
	{140, "TISCI_DEV_MCU_PSC0"},
	{141, "TISCI_DEV_MCSPI0"},
	{142, "TISCI_DEV_MCSPI1"},
	{143, "TISCI_DEV_MCSPI2"},
	{144, "TISCI_DEV_MCSPI3"},
	{145, "TISCI_DEV_MCSPI4"},
	{146, "TISCI_DEV_UART0"},
	{147, "TISCI_DEV_MCU_MCSPI0"},
	{148, "TISCI_DEV_MCU_MCSPI1"},
	{149, "TISCI_DEV_MCU_UART0"},
	{150, "TISCI_DEV_SPINLOCK0"},
	{151, "TISCI_DEV_TIMERMGR0"},
	{152, "TISCI_DEV_UART1"},
	{153, "TISCI_DEV_UART2"},
	{154, "TISCI_DEV_UART3"},
	{155, "TISCI_DEV_UART4"},
	{156, "TISCI_DEV_UART5"},
	{157, "TISCI_DEV_BOARD0"},
	{158, "TISCI_DEV_UART6"},
	{160, "TISCI_DEV_MCU_UART1"},
	{161, "TISCI_DEV_USB0"},
	{162, "TISCI_DEV_SERDES_10G0"},
	{163, "TISCI_DEV_PBIST0"},
	{164, "TISCI_DEV_PBIST1"},
	{165, "TISCI_DEV_PBIST2"},
	{166, "TISCI_DEV_PBIST3"},
	{167, "TISCI_DEV_COMPUTE_CLUSTER0_PBIST_0"},
};
