/*
 * AM243X RM Info
 *
 * Copyright (C) 2020 Texas Instruments Incorporated - https://www.ti.com/
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <tisci.h>
#include <socinfo.h>

struct ti_sci_rm_info am243x_rm_info[] = {
{0x0040, 1 , "TISCI_DEV_CMP_EVENT_INTROUTER0", 0, "RESASG_SUBTYPE_IR_OUTPUT" },
{0x00c0, 3 , "TISCI_DEV_MAIN_GPIOMUX_INTROUTER0", 0, "RESASG_SUBTYPE_IR_OUTPUT" },
{0x0140, 5 , "TISCI_DEV_MCU_MCU_GPIOMUX_INTROUTER0", 0, "RESASG_SUBTYPE_IR_OUTPUT" },
{0x0180, 6 , "TISCI_DEV_TIMESYNC_EVENT_INTROUTER0", 0, "RESASG_SUBTYPE_IR_OUTPUT" },
{0x0682, 26, "TISCI_DEV_DMASS0_BCDMA_0", 2, "RESASG_SUBTYPE_GLOBAL_EVENT_TRIGGER" },
{0x0683, 26, "TISCI_DEV_DMASS0_BCDMA_0", 3, "RESASG_SUBTYPE_UDMAP_GLOBAL_CONFIG" },
{0x068d, 26, "TISCI_DEV_DMASS0_BCDMA_0", 13, "RESASG_SUBTYPE_BCDMA_RING_BLOCK_COPY_CHAN" },
{0x068e, 26, "TISCI_DEV_DMASS0_BCDMA_0", 14, "RESASG_SUBTYPE_BCDMA_RING_SPLIT_TR_RX_CHAN" },
{0x068f, 26, "TISCI_DEV_DMASS0_BCDMA_0", 15, "RESASG_SUBTYPE_BCDMA_RING_SPLIT_TR_TX_CHAN" },
{0x06a0, 26, "TISCI_DEV_DMASS0_BCDMA_0", 32, "RESASG_SUBTYPE_BCDMA_BLOCK_COPY_CHAN" },
{0x06a1, 26, "TISCI_DEV_DMASS0_BCDMA_0", 33, "RESASG_SUBTYPE_BCDMA_SPLIT_TR_RX_CHAN" },
{0x06a2, 26, "TISCI_DEV_DMASS0_BCDMA_0", 34, "RESASG_SUBTYPE_BCDMA_SPLIT_TR_TX_CHAN" },
{0x070a, 28, "TISCI_DEV_DMASS0_INTAGGR_0", 10, "RESASG_SUBTYPE_IA_VINT" },
{0x070d, 28, "TISCI_DEV_DMASS0_INTAGGR_0", 13, "RESASG_SUBTYPE_GLOBAL_EVENT_SEVT" },
{0x070f, 28, "TISCI_DEV_DMASS0_INTAGGR_0", 15, "RESASG_SUBTYPE_IA_TIMERMGR_EVT_OES" },
{0x0710, 28, "TISCI_DEV_DMASS0_INTAGGR_0", 16, "RESASG_SUBTYPE_IA_PKTDMA_TX_CHAN_ERROR_OES" },
{0x0711, 28, "TISCI_DEV_DMASS0_INTAGGR_0", 17, "RESASG_SUBTYPE_IA_PKTDMA_TX_FLOW_COMPLETION_OES" },
{0x0712, 28, "TISCI_DEV_DMASS0_INTAGGR_0", 18, "RESASG_SUBTYPE_IA_PKTDMA_RX_CHAN_ERROR_OES" },
{0x0713, 28, "TISCI_DEV_DMASS0_INTAGGR_0", 19, "RESASG_SUBTYPE_IA_PKTDMA_RX_FLOW_COMPLETION_OES" },
{0x0714, 28, "TISCI_DEV_DMASS0_INTAGGR_0", 20, "RESASG_SUBTYPE_IA_PKTDMA_RX_FLOW_STARVATION_OES" },
{0x0715, 28, "TISCI_DEV_DMASS0_INTAGGR_0", 21, "RESASG_SUBTYPE_IA_PKTDMA_RX_FLOW_FIREWALL_OES" },
{0x0716, 28, "TISCI_DEV_DMASS0_INTAGGR_0", 22, "RESASG_SUBTYPE_IA_BCDMA_CHAN_ERROR_OES" },
{0x0717, 28, "TISCI_DEV_DMASS0_INTAGGR_0", 23, "RESASG_SUBTYPE_IA_BCDMA_CHAN_DATA_COMPLETION_OES" },
{0x0718, 28, "TISCI_DEV_DMASS0_INTAGGR_0", 24, "RESASG_SUBTYPE_IA_BCDMA_CHAN_RING_COMPLETION_OES" },
{0x0719, 28, "TISCI_DEV_DMASS0_INTAGGR_0", 25, "RESASG_SUBTYPE_IA_BCDMA_TX_CHAN_ERROR_OES" },
{0x071a, 28, "TISCI_DEV_DMASS0_INTAGGR_0", 26, "RESASG_SUBTYPE_IA_BCDMA_TX_CHAN_DATA_COMPLETION_OES" },
{0x071b, 28, "TISCI_DEV_DMASS0_INTAGGR_0", 27, "RESASG_SUBTYPE_IA_BCDMA_TX_CHAN_RING_COMPLETION_OES" },
{0x071c, 28, "TISCI_DEV_DMASS0_INTAGGR_0", 28, "RESASG_SUBTYPE_IA_BCDMA_RX_CHAN_ERROR_OES" },
{0x071d, 28, "TISCI_DEV_DMASS0_INTAGGR_0", 29, "RESASG_SUBTYPE_IA_BCDMA_RX_CHAN_DATA_COMPLETION_OES" },
{0x071e, 28, "TISCI_DEV_DMASS0_INTAGGR_0", 30, "RESASG_SUBTYPE_IA_BCDMA_RX_CHAN_RING_COMPLETION_OES" },
{0x0783, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 3, "RESASG_SUBTYPE_UDMAP_GLOBAL_CONFIG" },
{0x0790, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 16, "RESASG_SUBTYPE_PKTDMA_RING_UNMAPPED_TX_CHAN" },
{0x0791, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 17, "RESASG_SUBTYPE_PKTDMA_RING_CPSW_TX_CHAN" },
{0x0792, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 18, "RESASG_SUBTYPE_PKTDMA_RING_SAUL_TX_0_CHAN" },
{0x0793, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 19, "RESASG_SUBTYPE_PKTDMA_RING_SAUL_TX_1_CHAN" },
{0x0794, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 20, "RESASG_SUBTYPE_PKTDMA_RING_ICSSG_0_TX_CHAN" },
{0x0795, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 21, "RESASG_SUBTYPE_PKTDMA_RING_ICSSG_1_TX_CHAN" },
{0x0796, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 22, "RESASG_SUBTYPE_PKTDMA_RING_UNMAPPED_RX_CHAN" },
{0x0797, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 23, "RESASG_SUBTYPE_PKTDMA_RING_CPSW_RX_CHAN" },
{0x0798, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 24, "RESASG_SUBTYPE_PKTDMA_RING_SAUL_RX_0_CHAN" },
{0x0799, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 25, "RESASG_SUBTYPE_PKTDMA_RING_SAUL_RX_1_CHAN" },
{0x079a, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 26, "RESASG_SUBTYPE_PKTDMA_RING_SAUL_RX_2_CHAN" },
{0x079b, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 27, "RESASG_SUBTYPE_PKTDMA_RING_SAUL_RX_3_CHAN" },
{0x079c, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 28, "RESASG_SUBTYPE_PKTDMA_RING_ICSSG_0_RX_CHAN" },
{0x079d, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 29, "RESASG_SUBTYPE_PKTDMA_RING_ICSSG_1_RX_CHAN" },
{0x07a3, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 35, "RESASG_SUBTYPE_PKTDMA_UNMAPPED_TX_CHAN" },
{0x07a4, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 36, "RESASG_SUBTYPE_PKTDMA_CPSW_TX_CHAN" },
{0x07a5, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 37, "RESASG_SUBTYPE_PKTDMA_SAUL_TX_0_CHAN" },
{0x07a6, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 38, "RESASG_SUBTYPE_PKTDMA_SAUL_TX_1_CHAN" },
{0x07a7, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 39, "RESASG_SUBTYPE_PKTDMA_ICSSG_0_TX_CHAN" },
{0x07a8, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 40, "RESASG_SUBTYPE_PKTDMA_ICSSG_1_TX_CHAN" },
{0x07a9, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 41, "RESASG_SUBTYPE_PKTDMA_UNMAPPED_RX_CHAN" },
{0x07aa, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 42, "RESASG_SUBTYPE_PKTDMA_FLOW_UNMAPPED_RX_CHAN" },
{0x07ab, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 43, "RESASG_SUBTYPE_PKTDMA_CPSW_RX_CHAN" },
{0x07ac, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 44, "RESASG_SUBTYPE_PKTDMA_FLOW_CPSW_RX_CHAN" },
{0x07ad, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 45, "RESASG_SUBTYPE_PKTDMA_SAUL_RX_0_CHAN" },
{0x07ae, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 46, "RESASG_SUBTYPE_PKTDMA_FLOW_SAUL_RX_0_CHAN" },
{0x07af, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 47, "RESASG_SUBTYPE_PKTDMA_SAUL_RX_1_CHAN" },
{0x07b0, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 48, "RESASG_SUBTYPE_PKTDMA_FLOW_SAUL_RX_1_CHAN" },
{0x07b1, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 49, "RESASG_SUBTYPE_PKTDMA_SAUL_RX_2_CHAN" },
{0x07b2, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 50, "RESASG_SUBTYPE_PKTDMA_FLOW_SAUL_RX_2_CHAN" },
{0x07b3, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 51, "RESASG_SUBTYPE_PKTDMA_SAUL_RX_3_CHAN" },
{0x07b4, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 52, "RESASG_SUBTYPE_PKTDMA_FLOW_SAUL_RX_3_CHAN" },
{0x07b5, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 53, "RESASG_SUBTYPE_PKTDMA_ICSSG_0_RX_CHAN" },
{0x07b6, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 54, "RESASG_SUBTYPE_PKTDMA_FLOW_ICSSG_0_RX_CHAN" },
{0x07b7, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 55, "RESASG_SUBTYPE_PKTDMA_ICSSG_1_RX_CHAN" },
{0x07b8, 30, "TISCI_DEV_DMASS0_PKTDMA_0", 56, "RESASG_SUBTYPE_PKTDMA_FLOW_ICSSG_1_RX_CHAN" },
{0x0840, 33, "TISCI_DEV_DMASS0_RINGACC_0", 0 , "RESASG_SUBTYPE_RA_ERROR_OES" },
{0x084a, 33, "TISCI_DEV_DMASS0_RINGACC_0", 10, "RESASG_SUBTYPE_RA_VIRTID" },
{0x084c, 33, "TISCI_DEV_DMASS0_RINGACC_0", 12, "RESASG_SUBTYPE_RA_GENERIC_IPC" },
};
